# Generated by Django 5.2.8 on 2025-12-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='owner_profiles/'),
        ),
    ]
