# Generated by Django 5.2.8 on 2026-03-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_address_profile_phone_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
