# Generated by Django 5.2.8 on 2026-03-06 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0005_sharingoption_occupied_beds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED_AWAITING_PAYMENT', 'Approved Awaiting Payment'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('VACATED', 'Vacated')], default='PENDING', max_length=30)),
                ('source', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE_CONVERTED', 'Offline Converted')], default='ONLINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('vacated_at', models.DateTimeField(blank=True, null=True)),
                ('user_vacate_requested', models.BooleanField(default=False)),
                ('owner_vacate_approved', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('sharing_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.sharingoption')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('HELD_BY_OWNER', 'Deposit Paid'), ('RETURN_MARKED', 'Owner Marked Returned'), ('RETURNED', 'User Confirmed Returned'), ('PARTIAL_RETURNED', 'Partial Return Confirmed'), ('DISPUTED', 'Deposit Disputed')], default='HELD_BY_OWNER', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='OfflineTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RENT', 'Offline Rent'), ('DEPOSIT_RETURN', 'Deposit Return'), ('REDUCTION', 'Mess Reduction')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_CONFIRMATION', 'Waiting for User Confirmation'), ('SUCCESS', 'Confirmed'), ('DISPUTED', 'Disputed')], default='PENDING_CONFIRMATION', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_transactions', to='bookings.booking')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_account_id', models.CharField(max_length=200)),
                ('payments_enabled', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('occupied_at', models.DateTimeField(auto_now_add=True)),
                ('invitation_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('sharing_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.sharingoption')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('ADVANCE', 'Advance'), ('RENT', 'Rent'), ('DEPOSIT', 'Deposit'), ('FOOD', 'Food')], default='ADVANCE', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['booking', 'status'], name='bookings_pa_booking_bf00c8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'SUCCESS')), fields=('booking', 'payment_type'), name='unique_success_payment_per_booking'), models.UniqueConstraint(condition=models.Q(('status', 'CREATED')), fields=('booking',), name='one_active_payment_per_booking')],
            },
        ),
    ]
