# Generated by Django 5.2.8 on 2026-03-12 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_payment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trace_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
