# Generated by Django 5.2.8 on 2026-03-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment_trace_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_success_payment_per_booking',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='one_active_payment_per_booking',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED_AWAITING_PAYMENT', 'Approved Awaiting Payment'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('VACATED', 'Vacated')], default='PENDING', max_length=30),
        ),
    ]
