# Generated by Django 5.2.8 on 2026-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_payment_unique_success_payment_per_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED_AWAITING_PAYMENT', 'Approved Awaiting Payment'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('CONFIRMED', 'Confirmed'), ('VACATED', 'Vacated')], default='PENDING', max_length=30),
        ),
    ]
