# Generated by Django 5.2.8 on 2026-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Advance'), ('RENT', 'Rent'), ('DEPOSIT', 'Deposit'), ('FOOD', 'Food'), ('BALANCE', 'Balance')], default='ADVANCE', max_length=20),
        ),
    ]
