# Generated by Django 5.2.8 on 2026-03-30 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_payment_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='food_opt_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_opt_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_opted_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='frozen_rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='marked_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='marked_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='owner_return_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='paid_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerpaymentprofile',
            name='rent_due_day',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='status',
            field=models.CharField(choices=[('PENDING_RECEIPT', 'Awaiting Deposit'), ('PENDING_CONFIRMATION', 'Marked — Awaiting Confirmation'), ('HELD_BY_OWNER', 'Deposit Confirmed Held'), ('RETURN_MARKED', 'Owner Marked Returned'), ('RETURNED', 'User Confirmed Returned'), ('PARTIAL_RETURNED', 'Partial Return Confirmed')], default='PENDING_RECEIPT', max_length=30),
        ),
        migrations.AlterField(
            model_name='offlinetransaction',
            name='status',
            field=models.CharField(choices=[('PENDING_CONFIRMATION', 'Waiting for Confirmation'), ('SUCCESS', 'Confirmed'), ('DISPUTED', 'Disputed')], default='PENDING_CONFIRMATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='offlinetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RENT', 'Offline Rent'), ('FOOD', 'Offline Food'), ('DEPOSIT_RETURN', 'Deposit Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ADVANCE', 'Advance'), ('RENT', 'Rent'), ('DEPOSIT', 'Deposit'), ('FOOD', 'Food'), ('BALANCE', 'Balance Rent')], default='ADVANCE', max_length=20),
        ),
        migrations.CreateModel(
            name='FoodSubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('OPT_IN', 'Opt In'), ('OPT_OUT', 'Opt Out')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Owner Acknowledgement'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from_month', models.DateField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_requests', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_due_date', models.DateField()),
                ('rent_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID_ONLINE', 'Paid Online'), ('PAID_OFFLINE', 'Paid Offline'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('rent_paid_at', models.DateTimeField(blank=True, null=True)),
                ('food_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food_status', models.CharField(choices=[('NA', 'Not Applicable'), ('PENDING', 'Pending'), ('PAID_ONLINE', 'Paid Online'), ('PAID_OFFLINE', 'Paid Offline'), ('OVERDUE', 'Overdue')], default='NA', max_length=20)),
                ('food_paid_at', models.DateTimeField(blank=True, null=True)),
                ('rent_offline_confirmed_by_owner', models.BooleanField(default=False)),
                ('rent_offline_confirmed_by_user', models.BooleanField(default=False)),
                ('food_offline_confirmed_by_owner', models.BooleanField(default=False)),
                ('food_offline_confirmed_by_user', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='bookings.booking')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('booking', 'month')},
            },
        ),
        migrations.AddField(
            model_name='offlinetransaction',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_transactions', to='bookings.monthlyledger'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.monthlyledger'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_RECEIVED', 'Payment Received'), ('FOOD_REQUEST', 'Food Subscription Request'), ('FOOD_CANCELLED', 'Food Subscription Cancelled'), ('OFFLINE_MARK', 'Offline Payment Marked'), ('OFFLINE_CONFIRMED', 'Offline Payment Confirmed'), ('VACATE_REQUESTED', 'Vacate Requested'), ('DEPOSIT_RECEIVED', 'Deposit Received'), ('DEPOSIT_RETURNED', 'Deposit Returned'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.monthlyledger')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
