# Generated by Django 5.2.8 on 2026-04-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_food_opt_in_date_booking_food_opt_out_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID_CASH', 'Paid (Cash)'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('rent_paid_date', models.DateField(blank=True, null=True)),
                ('food_opted', models.BooleanField(default=False)),
                ('food_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('food_status', models.CharField(choices=[('NA', 'Not Applicable'), ('PENDING', 'Pending'), ('PAID_CASH', 'Paid (Cash)'), ('WAIVED', 'Waived')], default='NA', max_length=20)),
                ('food_paid_date', models.DateField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('HELD', 'Held by Owner'), ('RETURNED', 'Returned'), ('PARTIAL_RETURNED', 'Partial Return')], default='PENDING', max_length=20, null=True)),
                ('deposit_returned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_entries', to='bookings.tenantslot')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('slot', 'month')},
            },
        ),
    ]
