# Generated by Django 5.2.8 on 2026-04-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_offlineregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='property_id_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('PAYMENT_DUE', 'Payment Due'), ('PAYMENT_RECEIVED', 'Payment Received'), ('FOOD_REQUEST', 'Food Subscription Request'), ('FOOD_CANCELLED', 'Food Subscription Cancelled'), ('OFFLINE_MARK', 'Offline Payment Marked'), ('OFFLINE_CONFIRMED', 'Offline Payment Confirmed'), ('VACATE_REQUESTED', 'Vacate Requested'), ('VACATE_APPROVED', 'Vacate Approved'), ('DEPOSIT_RECEIVED', 'Deposit Received'), ('DEPOSIT_RETURNED', 'Deposit Returned'), ('BOOKING_APPROVED', 'Booking Approved'), ('BOOKING_REJECTED', 'Booking Rejected'), ('BOOKING_CREATED', 'Booking Created'), ('BOOKING_ACTIVE', 'Booking Active'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('ACCOUNT_APPROVED', 'Account Approved'), ('ACCOUNT_REJECTED', 'Account Rejected'), ('PROPERTY_APPROVED', 'Property Approved'), ('PROPERTY_REJECTED', 'Property Rejected'), ('PROPERTY_ACTIVE', 'Property Active')], max_length=30),
        ),
    ]
