# Generated by Django 5.2.8 on 2025-12-24 11:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('rules_and_regulations', models.TextField()),
                ('stay_type', models.CharField(choices=[('GENTS', 'Gents'), ('LADIES', 'Ladies'), ('UNISEX', 'Unisex')], max_length=10)),
                ('preferred_occupants', models.JSONField()),
                ('address_text', models.TextField()),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_ac', models.BooleanField()),
                ('parking_available', models.BooleanField()),
                ('food_provided', models.BooleanField()),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notice_period', models.PositiveIntegerField(blank=True, null=True)),
                ('wifi_available', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('visiting_hours', models.CharField(blank=True, max_length=255)),
                ('nearby_landmarks', models.TextField(blank=True)),
                ('floor_info', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='SharingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_type', models.PositiveSmallIntegerField()),
                ('total_beds', models.PositiveIntegerField()),
                ('available_beds', models.PositiveIntegerField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_options', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'sharing_type')},
            },
        ),
    ]
