# Generated by Django 5.2.8 on 2025-12-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_available',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rules_and_regulations',
            field=models.TextField(blank=True),
        ),
    ]
