# Generated by Django 5.2.8 on 2025-12-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='food_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_available',
            field=models.BooleanField(default=False),
        ),
    ]
