# Generated by Django 5.2.8 on 2026-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_address_text_alter_property_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingoption',
            name='occupied_beds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
