# Generated by Django 5.2.8 on 2026-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_sharingoption_occupied_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharingoption',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
