# Generated by Django 5.2.8 on 2026-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_sharingoption_advance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='food_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
